# Microservices
worker:
    build: ./services/worker
    environment:
        SERVICE_3000_NAME: "api_worker"
        SERVICE_3000_TAGS: "backend,api_worker"
        SERVICE_3000_CHECK_HTTP: "/health"
        SERVICE_3000_CHECK_INTERVAL: "15s"
        RABBIT_SERVER: "rabbit"
    expose:
        - 3000
    links:
        - rabbit
        - consul
api:
    build: ./services/api
    environment:
        SERVICE_3000_NAME: "api"
        SERVICE_3000_TAGS: "backend,api"
        SERVICE_3000_CHECK_HTTP: "/health"
        SERVICE_3000_CHECK_INTERVAL: "15s"
        RABBIT_SERVER: "rabbit"
        MONGO_SERVER: "mongo"
    expose:
        - 3000
    links:
        - rabbit
        - mongo
        - consul

# Discovery
consul:
    image: gliderlabs/consul-server
    command: -node consulserv -bootstrap -ui-dir /ui -client 0.0.0.0
    ports:
        - "8300:8300"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
registrator:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    links:
        - consul
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
# Infrastructure Services
loadbalancer:
    build: ./loadbalancer
    environment:
        SERVICE_80_NAME: "lb"
        SERVICE_80_TAGS: "lb"
    links:
        - consul
    ports:
        - "80:80"
mongo:
    image: mongo:3
    ports:
        - "27017:27017"
rabbit:
    image: rabbitmq:3-management
    expose:
        - 5672
    ports:
        - "15672:15672"
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=password
