version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: |
            TAG=2.0.0_$CIRCLE_BUILD_NUM
            docker build -t bunk/resume:latest -t bunk/resume:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push bunk/resume:$TAG
            docker push bunk/resume:latest
